parent=keycloak
import=common/keycloak

styles=css/login.css

# Localization
locales=de,en

# Meta tags
meta=viewport==width=device-width,initial-scale=1

# Favicon
favicon=/resources/img/favicon.ico

# Logo
kcLogoLink=https://www.xbillr.eu
kcLogoTitle=XBillr - Powered by SME Tools
