requires 'Mojolicious', '>= 9.0';
requires 'DBIx::Class', '>= 0.082840';
requires 'DBIx::Class::Schema::Loader', '>= 0.07049';
requires 'DBD::MariaDB', '>= 1.22';
requires 'DateTime', '>= 1.59';
requires 'DateTime::Format::MySQL', '>= 0.07';
requires 'JSON', '>= 4.05';
requires 'UUID::Tiny', '>= 1.04';
requires 'Math::BigFloat', '>= 1.0';
requires 'PDF::API2', '>= 2.040';
requires 'XML::LibXML', '>= 1.0';
# OpenAPI + OIDC
requires 'Mojolicious::Plugin::OpenAPI', '>= 3.0';
requires 'JSON::Validator', '>= 5.14';
requires 'Crypt::JWT', '>= 0.037';
requires 'Crypt::PK::RSA', '>= 0.087';
requires 'CryptX', '>= 0.082';
# requires 'XML::LibXML', '>= 2.0206';
requires 'Crypt::PBKDF2', '>= 0.161520';
requires 'Email::Sender', '>= 1.300035';
requires 'Email::Simple', '>= 2.218';
requires 'Email::Simple::Creator', '>= 1.424';
requires 'MIME::Base64', '>= 3.16';
# Mojolicious::Plugin::CORS ist optional, verwenden wir stattdessen manuelles CORS
# requires 'Mojolicious::Plugin::CORS', '>= 1.0';

on 'test' => sub {
    requires 'Test::More', '>= 1.302190';
#    requires 'Test::Mojo', '>= 9.0';
    requires 'Devel::Cover', '>= 1.38';
};

