-- XBillr Datenbankschema für MariaDB

CREATE DATABASE IF NOT EXISTS xbillr CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE xbillr;

-- Temporarily disable foreign key checks to allow table creation in any order
SET FOREIGN_KEY_CHECKS = 0;

-- Customers
CREATE TABLE IF NOT EXISTS customers (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address_id VARCHAR(36),
    -- Legacy fields for backward compatibility (deprecated, use address_id)
    address VARCHAR(255),
    zip_code VARCHAR(20),
    city VARCHAR(100),
    country VARCHAR(2) DEFAULT 'DE',
    tax_id VARCHAR(50),
    vat_id VARCHAR(50),
    email VARCHAR(255),
    payment_terms INTEGER,
    tenant VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_name (name),
    INDEX idx_customers_tenant (tenant),
    INDEX idx_address_id (address_id),
    FOREIGN KEY (address_id) REFERENCES addresses(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tenants (organisations; plan from config/plans.conf)
CREATE TABLE IF NOT EXISTS tenants (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    plan VARCHAR(50) NOT NULL DEFAULT 'free',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_name (name),
    INDEX idx_plan (plan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Suppliers
CREATE TABLE IF NOT EXISTS suppliers (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(2) NOT NULL DEFAULT 'DE',
    tax_id VARCHAR(50),
    vat_id VARCHAR(50),
    hra_hrb_number VARCHAR(50),
    email VARCHAR(255),
    bank_account VARCHAR(50),
    bank_name VARCHAR(255),
    iban VARCHAR(34),
    bic VARCHAR(11),
    default_tax_rate DOUBLE,
    logo TEXT,
    tenant VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_suppliers_tenant (tenant)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Hourly Rates
CREATE TABLE IF NOT EXISTS hourly_rates (
    id VARCHAR(36) PRIMARY KEY,
    customer_id VARCHAR(36) NOT NULL,
    rate DECIMAL(10,2) NOT NULL,
    rate_type VARCHAR(10) NOT NULL,
    description TEXT,
    valid_from DATE NOT NULL,
    valid_to DATE,
    tenant VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_customer (customer_id),
    INDEX idx_valid_from (valid_from),
    INDEX idx_hourly_rates_tenant (tenant),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Time Entries
CREATE TABLE IF NOT EXISTS time_entries (
    id VARCHAR(36) PRIMARY KEY,
    customer_id VARCHAR(36) NOT NULL,
    hourly_rate_id VARCHAR(36) NOT NULL,
    date DATE NOT NULL,
    hours DECIMAL(10,2) NOT NULL,
    description TEXT NOT NULL,
    week INTEGER NOT NULL,
    year INTEGER NOT NULL,
    tenant VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_customer (customer_id),
    INDEX idx_date (date),
    INDEX idx_week_year (year, week),
    INDEX idx_time_entries_tenant (tenant),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    FOREIGN KEY (hourly_rate_id) REFERENCES hourly_rates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Invoices
CREATE TABLE IF NOT EXISTS invoices (
    id VARCHAR(36) PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    customer_id VARCHAR(36) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    tax_rate DECIMAL(5,2) NOT NULL,
    tax_amount DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    tax_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    payment_terms INTEGER,
    due_date DATE,
    xrechnung_xml TEXT,
    archived BOOLEAN NOT NULL DEFAULT 0,
    archived_at DATETIME,
    tenant VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_customer (customer_id),
    INDEX idx_invoice_number (invoice_number),
    INDEX idx_archived (archived),
    INDEX idx_invoices_tenant (tenant),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Invoice Items
CREATE TABLE IF NOT EXISTS invoice_items (
    id VARCHAR(36) PRIMARY KEY,
    invoice_id VARCHAR(36) NOT NULL,
    time_entry_id TEXT NOT NULL,
    description TEXT NOT NULL,
    hours DECIMAL(10,2) NOT NULL,
    rate DECIMAL(10,2) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    rate_type VARCHAR(10),
    INDEX idx_invoice (invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Timesheets
CREATE TABLE IF NOT EXISTS timesheets (
    id VARCHAR(36) PRIMARY KEY,
    customer_id VARCHAR(36) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    pdf_data LONGBLOB,
    description TEXT,
    archived BOOLEAN NOT NULL DEFAULT 0,
    archived_at DATETIME,
    created_at DATETIME NOT NULL,
    INDEX idx_customer (customer_id),
    INDEX idx_date_range (date_from, date_to),
    INDEX idx_archived (archived),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Activity Logs
CREATE TABLE IF NOT EXISTS activity_logs (
    id VARCHAR(36) PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(36),
    details TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_created_at (created_at),
    INDEX idx_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ISO 3166-1 Countries
CREATE TABLE IF NOT EXISTS countries (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    alpha2 CHAR(2) NOT NULL UNIQUE,
    alpha3 CHAR(3) NOT NULL UNIQUE,
    `numeric` CHAR(3) NOT NULL UNIQUE,
    name_de VARCHAR(255) NOT NULL,
    name_en VARCHAR(255) NOT NULL,
    INDEX idx_alpha2 (alpha2),
    INDEX idx_alpha3 (alpha3),
    INDEX idx_numeric (`numeric`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ISO 4217 Currencies
CREATE TABLE IF NOT EXISTS currencies (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    alpha3 CHAR(3) NOT NULL UNIQUE,
    `numeric` CHAR(3) NOT NULL,
    currency_sign VARCHAR(10),
    name_de VARCHAR(255) NOT NULL,
    name_en VARCHAR(255) NOT NULL,
    INDEX idx_alpha3 (alpha3),
    INDEX idx_numeric (`numeric`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Country Currencies (many-to-many relationship)
CREATE TABLE IF NOT EXISTS country_currencies (
    country_id INTEGER NOT NULL,
    currency_id INTEGER NOT NULL,
    PRIMARY KEY (country_id, currency_id),
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE,
    FOREIGN KEY (currency_id) REFERENCES currencies(id) ON DELETE CASCADE,
    INDEX idx_country_id (country_id),
    INDEX idx_currency_id (currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Addresses (reusable address structure)
CREATE TABLE IF NOT EXISTS addresses (
    id VARCHAR(36) PRIMARY KEY,
    street VARCHAR(255),
    building_number VARCHAR(20),
    address_line_1 VARCHAR(255),
    address_line_2 VARCHAR(255),
    post_code VARCHAR(20),
    town_name VARCHAR(255),
    country_sub_division VARCHAR(100),
    country_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_country_id (country_id),
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Countries
INSERT INTO countries (id, alpha2, alpha3, `numeric`, name_de, name_en) VALUES
(1, 'AD', 'AND', '20', 'Andorra', 'Andorra'),
(2, 'AE', 'ARE', '784', 'Vereinigte Arabische Emirate', 'United Arab Emirates'),
(3, 'AF', 'AFG', '4', 'Afghanistan', 'Afghanistan'),
(4, 'AG', 'ATG', '28', 'Antigua und Barbuda', 'Antigua and Barbuda'),
(5, 'AI', 'AIA', '660', 'Anguilla', 'Anguilla'),
(6, 'AL', 'ALB', '8', 'Albanien', 'Albania'),
(7, 'AM', 'ARM', '51', 'Armenien', 'Armenia'),
(8, 'AO', 'AGO', '24', 'Angola', 'Angola'),
(9, 'AQ', 'ATA', '10', 'Antarktis', 'Antarctica'),
(10, 'AR', 'ARG', '32', 'Argentinien', 'Argentina'),
(11, 'AS', 'ASM', '16', 'Amerikanisch-Samoa', 'American Samoa'),
(12, 'AT', 'AUT', '40', 'Österreich', 'Austria'),
(13, 'AU', 'AUS', '36', 'Australien', 'Australia'),
(14, 'AW', 'ABW', '533', 'Aruba', 'Aruba'),
(15, 'AX', 'ALA', '248', 'Åland', 'Åland Islands'),
(16, 'AZ', 'AZE', '31', 'Aserbaidschan', 'Azerbaijan'),
(17, 'BA', 'BIH', '70', 'Bosnien und Herzegowina', 'Bosnia and Herzegovina'),
(18, 'BB', 'BRB', '52', 'Barbados', 'Barbados'),
(19, 'BD', 'BGD', '50', 'Bangladesch', 'Bangladesh'),
(20, 'BE', 'BEL', '56', 'Belgien', 'Belgium'),
(21, 'BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso'),
(22, 'BG', 'BGR', '100', 'Bulgarien', 'Bulgaria'),
(23, 'BH', 'BHR', '48', 'Bahrain', 'Bahrain'),
(24, 'BI', 'BDI', '108', 'Burundi', 'Burundi'),
(25, 'BJ', 'BEN', '204', 'Benin', 'Benin'),
(26, 'BL', 'BLM', '652', 'Sankt Barthélemy', 'Saint Barthélemy'),
(27, 'BM', 'BMU', '60', 'Bermuda', 'Bermuda'),
(28, 'BN', 'BRN', '96', 'Brunei Darussalam', 'Brunei Darussalam'),
(29, 'BO', 'BOL', '68', 'Bolivien', 'Bolivia'),
(30, 'BQ', 'BES', '535', 'Bonaire', ' Sint Eustatius und Saba'),
(31, 'BR', 'BRA', '76', 'Brasilien', 'Brazil'),
(32, 'BS', 'BHS', '44', 'Bahamas', 'Bahamas'),
(33, 'BT', 'BTN', '64', 'Bhutan', 'Bhutan'),
(34, 'BV', 'BVT', '74', 'Bouvetinsel', 'Bouvet Island'),
(35, 'BW', 'BWA', '72', 'Botsuana', 'Botswana'),
(36, 'BY', 'BLR', '112', 'Weißrussland', 'Belarus'),
(37, 'BZ', 'BLZ', '84', 'Belize', 'Belize'),
(38, 'CA', 'CAN', '124', 'Kanada', 'Canada'),
(39, 'CC', 'CCK', '166', 'Kokosinseln', 'Cocos (Keeling) Islands'),
(40, 'CD', 'COD', '180', 'Kongo', ' Demokratische Republik'),
(41, 'CF', 'CAF', '140', 'Zentralafrikanische Republik', 'Central African Republic'),
(42, 'CG', 'COG', '178', 'Kongo', 'Congo'),
(43, 'CH', 'CHE', '756', 'Schweiz', 'Switzerland'),
(44, 'CI', 'CIV', '384', 'Côte d''Ivoire', 'Côte d''Ivoire'),
(45, 'CK', 'COK', '184', 'Cookinseln', 'Cook Islands'),
(46, 'CL', 'CHL', '152', 'Chile', 'Chile'),
(47, 'CM', 'CMR', '120', 'Kamerun', 'Cameroon'),
(48, 'CN', 'CHN', '156', 'China', 'China'),
(49, 'CO', 'COL', '170', 'Kolumbien', 'Colombia'),
(50, 'CR', 'CRI', '188', 'Costa Rica', 'Costa Rica'),
(51, 'CU', 'CUB', '192', 'Kuba', 'Cuba'),
(52, 'CV', 'CPV', '132', 'Cabo Verde', 'Cabo Verde'),
(53, 'CW', 'CUW', '531', 'Curaçao', 'Curaçao'),
(54, 'CX', 'CXR', '162', 'Weihnachtsinsel', 'Christmas Island'),
(55, 'CY', 'CYP', '196', 'Zypern', 'Cyprus'),
(56, 'CZ', 'CZE', '203', 'Tschechien', 'Czechia'),
(57, 'DE', 'DEU', '276', 'Deutschland', 'Germany'),
(58, 'DJ', 'DJI', '262', 'Dschibuti', 'Djibouti'),
(59, 'DK', 'DNK', '208', 'Dänemark', 'Denmark'),
(60, 'DM', 'DMA', '212', 'Dominica', 'Dominica'),
(61, 'DO', 'DOM', '214', 'Dominikanische Republik', 'Dominican Republic'),
(62, 'DZ', 'DZA', '12', 'Algerien', 'Algeria'),
(63, 'EC', 'ECU', '218', 'Ecuador', 'Ecuador'),
(64, 'EE', 'EST', '233', 'Estland', 'Estonia'),
(65, 'EG', 'EGY', '818', 'Ägypten', 'Egypt'),
(66, 'EH', 'ESH', '732', 'Westsahara', 'Western Sahara'),
(67, 'ER', 'ERI', '232', 'Eritrea', 'Eritrea'),
(68, 'ES', 'ESP', '724', 'Spanien', 'Spain'),
(69, 'ET', 'ETH', '231', 'Äthiopien', 'Ethiopia'),
(70, 'FI', 'FIN', '246', 'Finnland', 'Finland'),
(71, 'FJ', 'FJI', '242', 'Fidschi', 'Fiji'),
(72, 'FK', 'FLK', '238', 'Falklandinseln', 'Falkland Islands (Malvinas)'),
(73, 'FM', 'FSM', '583', 'Mikronesien', 'Micronesia'),
(74, 'FO', 'FRO', '234', 'Färöer', 'Faroe Islands'),
(75, 'FR', 'FRA', '250', 'Frankreich', 'France'),
(76, 'GA', 'GAB', '266', 'Gabun', 'Gabon'),
(77, 'GB', 'GBR', '826', 'Vereinigtes Königreich', 'United Kingdom'),
(78, 'GD', 'GRD', '308', 'Grenada', 'Grenada'),
(79, 'GE', 'GEO', '268', 'Georgien', 'Georgia'),
(80, 'GF', 'GUF', '254', 'Französisch-Guayana', 'French Guiana'),
(81, 'GG', 'GGY', '831', 'Guernsey', 'Guernsey'),
(82, 'GH', 'GHA', '288', 'Ghana', 'Ghana'),
(83, 'GI', 'GIB', '292', 'Gibraltar', 'Gibraltar'),
(84, 'GL', 'GRL', '304', 'Grönland', 'Greenland'),
(85, 'GM', 'GMB', '270', 'Gambia', 'Gambia'),
(86, 'GN', 'GIN', '324', 'Guinea', 'Guinea'),
(87, 'GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe'),
(88, 'GQ', 'GNQ', '226', 'Äquatorialguinea', 'Equatorial Guinea'),
(89, 'GR', 'GRC', '300', 'Griechenland', 'Greece'),
(90, 'GS', 'SGS', '239', 'Südgeorgien und die Südlichen Sandwichinseln', 'South Georgia and the South Sandwich Islands'),
(91, 'GT', 'GTM', '320', 'Guatemala', 'Guatemala'),
(92, 'GU', 'GUM', '316', 'Guam', 'Guam'),
(93, 'GW', 'GNB', '624', 'Guinea-Bissau', 'Guinea-Bissau'),
(94, 'GY', 'GUY', '328', 'Guyana', 'Guyana'),
(95, 'HK', 'HKG', '344', 'Hongkong', 'Hong Kong'),
(96, 'HM', 'HMD', '334', 'Heard und McDonaldinseln', 'Heard Island and McDonald Islands'),
(97, 'HN', 'HND', '340', 'Honduras', 'Honduras'),
(98, 'HR', 'HRV', '191', 'Kroatien', 'Croatia'),
(99, 'HT', 'HTI', '332', 'Haiti', 'Haiti'),
(100, 'HU', 'HUN', '348', 'Ungarn', 'Hungary'),
(101, 'ID', 'IDN', '360', 'Indonesien', 'Indonesia'),
(102, 'IE', 'IRL', '372', 'Irland', 'Ireland'),
(103, 'IL', 'ISR', '376', 'Israel', 'Israel'),
(104, 'IM', 'IMN', '833', 'Isle of Man', 'Isle of Man'),
(105, 'IN', 'IND', '356', 'Indien', 'India'),
(106, 'IO', 'IOT', '86', 'Britisches Territorium im Indischen Ozean', 'British Indian Ocean Territory'),
(107, 'IQ', 'IRQ', '368', 'Irak', 'Iraq'),
(108, 'IR', 'IRN', '364', 'Iran', 'Iran'),
(109, 'IS', 'ISL', '352', 'Island', 'Iceland'),
(110, 'IT', 'ITA', '380', 'Italien', 'Italy'),
(111, 'JE', 'JEY', '832', 'Jersey', 'Jersey'),
(112, 'JM', 'JAM', '388', 'Jamaika', 'Jamaica'),
(113, 'JO', 'JOR', '400', 'Jordanien', 'Jordan'),
(114, 'JP', 'JPN', '392', 'Japan', 'Japan'),
(115, 'KE', 'KEN', '404', 'Kenia', 'Kenya'),
(116, 'KG', 'KGZ', '417', 'Kirgisistan', 'Kyrgyzstan'),
(117, 'KH', 'KHM', '116', 'Kambodscha', 'Cambodia'),
(118, 'KI', 'KIR', '296', 'Kiribati', 'Kiribati'),
(119, 'KM', 'COM', '174', 'Komoren', 'Comoros'),
(120, 'KN', 'KNA', '659', 'St. Kitts und Nevis', 'Saint Kitts and Nevis'),
(121, 'KP', 'PRK', '408', 'Korea', ' Demokratische Volksrepublik'),
(122, 'KR', 'KOR', '410', 'Korea', ' Republik'),
(123, 'KW', 'KWT', '414', 'Kuwait', 'Kuwait'),
(124, 'KY', 'CYM', '136', 'Kaimaninseln', 'Cayman Islands'),
(125, 'KZ', 'KAZ', '398', 'Kasachstan', 'Kazakhstan'),
(126, 'LA', 'LAO', '418', 'Laos', 'Laos'),
(127, 'LB', 'LBN', '422', 'Libanon', 'Lebanon'),
(128, 'LC', 'LCA', '662', 'St. Lucia', 'Saint Lucia'),
(129, 'LI', 'LIE', '438', 'Liechtenstein', 'Liechtenstein'),
(130, 'LK', 'LKA', '144', 'Sri Lanka', 'Sri Lanka'),
(131, 'LR', 'LBR', '430', 'Liberia', 'Liberia'),
(132, 'LS', 'LSO', '426', 'Lesotho', 'Lesotho'),
(133, 'LT', 'LTU', '440', 'Litauen', 'Lithuania'),
(134, 'LU', 'LUX', '442', 'Luxemburg', 'Luxembourg'),
(135, 'LV', 'LVA', '428', 'Lettland', 'Latvia'),
(136, 'LY', 'LBY', '434', 'Libyen', 'Libya'),
(137, 'MA', 'MAR', '504', 'Marokko', 'Morocco'),
(138, 'MC', 'MCO', '492', 'Monaco', 'Monaco'),
(139, 'MD', 'MDA', '498', 'Moldau', ' Republik'),
(140, 'ME', 'MNE', '499', 'Montenegro', 'Montenegro'),
(141, 'MF', 'MAF', '663', 'Sankt Martin', 'Saint Martin (French part)'),
(142, 'MG', 'MDG', '450', 'Madagaskar', 'Madagascar'),
(143, 'MH', 'MHL', '584', 'Marshallinseln', 'Marshall Islands'),
(144, 'MK', 'MKD', '807', 'Nordmazedonien', 'North Macedonia'),
(145, 'ML', 'MLI', '466', 'Mali', 'Mali'),
(146, 'MM', 'MMR', '104', 'Myanmar', 'Myanmar'),
(147, 'MN', 'MNG', '496', 'Mongolei', 'Mongolia'),
(148, 'MO', 'MAC', '446', 'Macau', 'Macao'),
(149, 'MP', 'MNP', '580', 'Nördliche Marianen', 'Northern Mariana Islands'),
(150, 'MQ', 'MTQ', '474', 'Martinique', 'Martinique'),
(151, 'MR', 'MRT', '478', 'Mauretanien', 'Mauritania'),
(152, 'MS', 'MSR', '500', 'Montserrat', 'Montserrat'),
(153, 'MT', 'MLT', '470', 'Malta', 'Malta'),
(154, 'MU', 'MUS', '480', 'Mauritius', 'Mauritius'),
(155, 'MV', 'MDV', '462', 'Malediven', 'Maldives'),
(156, 'MW', 'MWI', '454', 'Malawi', 'Malawi'),
(157, 'MX', 'MEX', '484', 'Mexiko', 'Mexico'),
(158, 'MY', 'MYS', '458', 'Malaysia', 'Malaysia'),
(159, 'MZ', 'MOZ', '508', 'Mosambik', 'Mozambique'),
(160, 'NA', 'NAM', '516', 'Namibia', 'Namibia'),
(161, 'NC', 'NCL', '540', 'Neukaledonien', 'New Caledonia'),
(162, 'NE', 'NER', '562', 'Niger', 'Niger'),
(163, 'NF', 'NFK', '574', 'Norfolkinsel', 'Norfolk Island'),
(164, 'NG', 'NGA', '566', 'Nigeria', 'Nigeria'),
(165, 'NI', 'NIC', '558', 'Nicaragua', 'Nicaragua'),
(166, 'NL', 'NLD', '528', 'Niederlande', 'Netherlands'),
(167, 'NO', 'NOR', '578', 'Norwegen', 'Norway'),
(168, 'NP', 'NPL', '524', 'Nepal', 'Nepal'),
(169, 'NR', 'NRU', '520', 'Nauru', 'Nauru'),
(170, 'NU', 'NIU', '570', 'Niue', 'Niue'),
(171, 'NZ', 'NZL', '554', 'Neuseeland', 'New Zealand'),
(172, 'OM', 'OMN', '512', 'Oman', 'Oman'),
(173, 'PA', 'PAN', '591', 'Panama', 'Panama'),
(174, 'PE', 'PER', '604', 'Peru', 'Peru'),
(175, 'PF', 'PYF', '258', 'Französisch-Polynesien', 'French Polynesia'),
(176, 'PG', 'PNG', '598', 'Papua-Neuguinea', 'Papua New Guinea'),
(177, 'PH', 'PHL', '608', 'Philippinen', 'Philippines'),
(178, 'PK', 'PAK', '586', 'Pakistan', 'Pakistan'),
(179, 'PL', 'POL', '616', 'Polen', 'Poland'),
(180, 'PM', 'SPM', '666', 'St. Pierre und Miquelon', 'Saint Pierre and Miquelon'),
(181, 'PN', 'PCN', '612', 'Pitcairninseln', 'Pitcairn'),
(182, 'PR', 'PRI', '630', 'Puerto Rico', 'Puerto Rico'),
(183, 'PS', 'PSE', '275', 'Palästina', 'Palestine'),
(184, 'PT', 'PRT', '620', 'Portugal', 'Portugal'),
(185, 'PW', 'PLW', '585', 'Palau', 'Palau'),
(186, 'PY', 'PRY', '600', 'Paraguay', 'Paraguay'),
(187, 'QA', 'QAT', '634', 'Katar', 'Qatar'),
(188, 'RE', 'REU', '638', 'Réunion', 'Réunion'),
(189, 'RO', 'ROU', '642', 'Rumänien', 'Romania'),
(190, 'RS', 'SRB', '688', 'Serbien', 'Serbia'),
(191, 'RU', 'RUS', '643', 'Russland', 'Russian Federation'),
(192, 'RW', 'RWA', '646', 'Ruanda', 'Rwanda'),
(193, 'SA', 'SAU', '682', 'Saudi-Arabien', 'Saudi Arabia'),
(194, 'SB', 'SLB', '90', 'Salomonen', 'Solomon Islands'),
(195, 'SC', 'SYC', '690', 'Seychellen', 'Seychelles'),
(196, 'SD', 'SDN', '729', 'Sudan', 'Sudan'),
(197, 'SE', 'SWE', '752', 'Schweden', 'Sweden'),
(198, 'SG', 'SGP', '702', 'Singapur', 'Singapore'),
(199, 'SH', 'SHN', '654', 'St. Helena', ' Ascension und Tristan da Cunha'),
(200, 'SI', 'SVN', '705', 'Slowenien', 'Slovenia'),
(201, 'SJ', 'SJM', '744', 'Svalbard und Jan Mayen', 'Svalbard and Jan Mayen'),
(202, 'SK', 'SVK', '703', 'Slowakei', 'Slovakia'),
(203, 'SL', 'SLE', '694', 'Sierra Leone', 'Sierra Leone'),
(204, 'SM', 'SMR', '674', 'San Marino', 'San Marino'),
(205, 'SN', 'SEN', '686', 'Senegal', 'Senegal'),
(206, 'SO', 'SOM', '706', 'Somalia', 'Somalia'),
(207, 'SR', 'SUR', '740', 'Suriname', 'Suriname'),
(208, 'SS', 'SSD', '728', 'Südsudan', 'South Sudan'),
(209, 'ST', 'STP', '678', 'São Tomé und Príncipe', 'Sao Tome and Principe'),
(210, 'SV', 'SLV', '222', 'El Salvador', 'El Salvador'),
(211, 'SX', 'SXM', '534', 'Sint Maarten', 'Sint Maarten (Dutch part)'),
(212, 'SY', 'SYR', '760', 'Syrien', 'Syrian Arab Republic'),
(213, 'SZ', 'SWZ', '748', 'Eswatini', 'Eswatini'),
(214, 'TC', 'TCA', '796', 'Turks- und Caicosinseln', 'Turks and Caicos Islands'),
(215, 'TD', 'TCD', '148', 'Tschad', 'Chad'),
(216, 'TF', 'ATF', '260', 'Französische Süd- und Antarktisgebiete', 'French Southern Territories'),
(217, 'TG', 'TGO', '768', 'Togo', 'Togo'),
(218, 'TH', 'THA', '764', 'Thailand', 'Thailand'),
(219, 'TJ', 'TJK', '762', 'Tadschikistan', 'Tajikistan'),
(220, 'TK', 'TKL', '772', 'Tokelau', 'Tokelau'),
(221, 'TL', 'TLS', '626', 'Timor-Leste', 'Timor-Leste'),
(222, 'TM', 'TKM', '795', 'Turkmenistan', 'Turkmenistan'),
(223, 'TN', 'TUN', '788', 'Tunesien', 'Tunisia'),
(224, 'TO', 'TON', '776', 'Tonga', 'Tonga'),
(225, 'TR', 'TUR', '792', 'Türkei', 'Türkiye'),
(226, 'TT', 'TTO', '780', 'Trinidad und Tobago', 'Trinidad and Tobago'),
(227, 'TV', 'TUV', '798', 'Tuvalu', 'Tuvalu'),
(228, 'TW', 'TWN', '158', 'Taiwan', 'Taiwan'),
(229, 'TZ', 'TZA', '834', 'Tansania', ' Vereinigte Republik'),
(230, 'UA', 'UKR', '804', 'Ukraine', 'Ukraine'),
(231, 'UG', 'UGA', '800', 'Uganda', 'Uganda'),
(232, 'UM', 'UMI', '581', 'Kleinere Amerikanische Überseeinseln', 'United States Minor Outlying Islands'),
(233, 'US', 'USA', '840', 'Vereinigte Staaten', 'United States of America'),
(234, 'UY', 'URY', '858', 'Uruguay', 'Uruguay'),
(235, 'UZ', 'UZB', '860', 'Usbekistan', 'Uzbekistan'),
(236, 'VA', 'VAT', '336', 'Vatikanstadt', 'Holy See'),
(237, 'VC', 'VCT', '670', 'St. Vincent und die Grenadinen', 'Saint Vincent and the Grenadines'),
(238, 'VE', 'VEN', '862', 'Venezuela', 'Venezuela'),
(239, 'VG', 'VGB', '92', 'Britische Jungferninseln', 'Virgin Islands'),
(240, 'VI', 'VIR', '850', 'Amerikanische Jungferninseln', 'Virgin Islands'),
(241, 'VN', 'VNM', '704', 'Vietnam', 'Viet Nam'),
(242, 'VU', 'VUT', '548', 'Vanuatu', 'Vanuatu'),
(243, 'WF', 'WLF', '876', 'Wallis und Futuna', 'Wallis and Futuna'),
(244, 'WS', 'WSM', '882', 'Samoa', 'Samoa'),
(245, 'YE', 'YEM', '887', 'Jemen', 'Yemen'),
(246, 'YT', 'MYT', '175', 'Mayotte', 'Mayotte'),
(247, 'ZA', 'ZAF', '710', 'Südafrika', 'South Africa'),
(248, 'ZM', 'ZMB', '894', 'Sambia', 'Zambia'),
(249, 'ZW', 'ZWE', '716', 'Simbabwe', 'Zimbabwe');

-- Currencies
INSERT INTO currencies (id, alpha3, `numeric`, currency_sign, name_de, name_en) VALUES
(1, 'AED', '784', 'د.إ', 'Vereinigte Arabische Emirate Dirham', 'United Arab Emirates Dirham'),
(2, 'AFN', '971', '؋', 'Afghanischer Afghani', 'Afghan Afghani'),
(3, 'ALL', '8', 'L', 'Albanischer Lek', 'Albanian Lek'),
(4, 'AMD', '51', '֏', 'Armenischer Dram', 'Armenian Dram'),
(5, 'ANG', '532', 'ƒ', 'Niederländische-Antillen-Gulden', 'Netherlands Antillean Guilder'),
(6, 'AOA', '976', 'Kz', 'Angolanischer Kwanza', 'Angolan Kwanza'),
(7, 'ARS', '36', '$', 'Argentinischer Peso', 'Argentine Peso'),
(8, 'AUD', '36', '$', 'Australischer Dollar', 'Australian Dollar'),
(9, 'AWG', '571', 'ƒ', 'Aruba-Florin', 'Aruban Florin'),
(10, 'AZN', '944', '₼', 'Aserbaidschan-Manat', 'Azerbaijani Manat'),
(11, 'BAM', '977', 'KM', 'Bosnien und Herzegowina Konvertible Mark', 'Bosnia-Herzegovina Convertible Mark'),
(12, 'BBD', '52', '$', 'Barbados-Dollar', 'Barbadian Dollar'),
(13, 'BDT', '50', '৳', 'Bangladesch-Taka', 'Bangladeshi Taka'),
(14, 'BGN', '975', 'лв.', 'Bulgarischer Lew', 'Bulgarian Lev'),
(15, 'BHD', '48', '.د.ب', 'Bahrain-Dinar', 'Bahraini Dinar'),
(16, 'BIF', '108', 'Fr', 'Burundi-Franc', 'Burundian Franc'),
(17, 'BMD', '60', '$', 'Bermuda-Dollar', 'Bermudan Dollar'),
(18, 'BND', '96', '$', 'Brunei-Dollar', 'Brunei Dollar'),
(19, 'BOB', '68', 'Bs.', 'Bolivianischer Boliviano', 'Bolivian Boliviano'),
(20, 'BRL', '986', 'R$', 'Brasilianischer Real', 'Brazilian Real'),
(21, 'BSD', '44', '$', 'Bahamas-Dollar', 'Bahamian Dollar'),
(22, 'BTN', '64', 'NU.', 'Bhutanischer Ngultrum', 'Bhutanese Ngultrum'),
(23, 'BWP', '72', 'P', 'Botswanischer Pula', 'Botswanan Pula'),
(24, 'BYN', '933', 'Br', 'Weißrussischer Rubel', 'Belarusian Ruble'),
(25, 'BZD', '84', 'BZ$', 'Belize-Dollar', 'Belize Dollar'),
(26, 'CAD', '124', '$', 'Kanadischer Dollar', 'Canadian Dollar'),
(27, 'CDF', '976', 'FC', 'Kongo-Franc', 'Congolese Franc'),
(28, 'CHF', '756', 'CHF', 'Schweizer Franken', 'Swiss Franc'),
(29, 'CLP', '152', '$', 'Chilenischer Peso', 'Chilean Peso'),
(30, 'CNY', '156', '¥', 'Chinesischer Yuan Renminbi', 'Chinese Yuan'),
(31, 'COP', '170', '$', 'Kolumbianischer Peso', 'Colombian Peso'),
(32, 'CRC', '188', '₡', 'Costa-Rica-Colón', 'Costa Rican Colón'),
(33, 'CUC', '931', '$', 'Kubanischer Peso (konvertibel)', 'Cuban Convertible Peso'),
(34, 'CUP', '192', '$', 'Kubanischer Peso', 'Cuban Peso'),
(35, 'CVE', '132', '$', 'Cabo-Verde-Escudo', 'Cape Verdean Escudo'),
(36, 'CZK', '203', 'Kč', 'Tschechische Krone', 'Czech Koruna'),
(37, 'DJF', '262', 'Fr', 'Dschibuti-Franc', 'Djiboutian Franc'),
(38, 'DKK', '208', 'kr', 'Dänische Krone', 'Danish Krone'),
(39, 'DOP', '214', '$', 'Dominikanischer Peso', 'Dominican Peso'),
(40, 'DZD', '12', 'د.ج', 'Algerischer Dinar', 'Algerian Dinar'),
(41, 'EGP', '818', '£', 'Ägyptisches Pfund', 'Egyptian Pound'),
(42, 'ERN', '15', 'Nfk', 'Eritreischer Nakfa', 'Eritrean Nakfa'),
(43, 'ETB', '230', 'Br', 'Äthiopischer Birr', 'Ethiopian Birr'),
(44, 'EUR', '978', '€', 'Euro', 'Euro'),
(45, 'FJD', '242', '$', 'Fidschi-Dollar', 'Fijian Dollar'),
(46, 'GBP', '826', '£', 'Britisches Pfund', 'British Pound'),
(47, 'GEL', '981', 'ლ', 'Georgischer Lari', 'Georgian Lari'),
(48, 'GHS', '936', '₵', 'Ghanaischer Cedi', 'Ghanaian Cedi'),
(49, 'GIP', '292', '£', 'Gibraltar-Pfund', 'Gibraltar Pound'),
(50, 'GMD', '270', 'D', 'Gambia-Dalasi', 'Gambian Dalasi'),
(51, 'GNF', '324', 'Fr', 'Guinea-Franc', 'Guinean Franc'),
(52, 'GTQ', '320', 'Q', 'Guatemaltekischer Quetzal', 'Guatemalan Quetzal'),
(53, 'GYD', '328', '$', 'Guyana-Dollar', 'Guyanese Dollar'),
(54, 'HKD', '344', '$', 'Hongkong-Dollar', 'Hong Kong Dollar'),
(55, 'HNL', '340', 'L', 'Honduranischer Lempira', 'Honduran Lempira'),
(56, 'HRK', '191', 'kn', 'Kroatische Kuna', 'Croatian Kuna'),
(57, 'HTG', '332', 'G', 'Haitianische Gourde', 'Haitian Gourde'),
(58, 'HUF', '348', 'Ft', 'Ungarischer Forint', 'Hungarian Forint'),
(59, 'IDR', '360', 'Rp', 'Indonesische Rupiah', 'Indonesian Rupiah'),
(60, 'ILS', '376', '₪', 'Israelischer Schekel', 'Israeli New Shekel'),
(61, 'INR', '356', '₹', 'Indische Rupie', 'Indian Rupee'),
(62, 'IQD', '368', 'ع.د', 'Irakischer Dinar', 'Iraqi Dinar'),
(63, 'IRR', '364', '﷼', 'Iranischer Rial', 'Iranian Rial'),
(64, 'ISK', '352', 'kr', 'Isländische Krone', 'Icelandic Króna'),
(65, 'JMD', '388', '$', 'Jamaika-Dollar', 'Jamaican Dollar'),
(66, 'JOD', '400', 'د.ا', 'Jordanischer Dinar', 'Jordanian Dinar'),
(67, 'JPY', '392', '¥', 'Japanischer Yen', 'Japanese Yen'),
(68, 'KES', '404', '/', 'Kenia-Schilling', 'Kenyan Shilling'),
(69, 'KGS', '417', 'с', 'Kirgisischer Som', 'Kyrgystani Som'),
(70, 'KHR', '410', '៛', 'Kambodschanischer Riel', 'Cambodian Riel'),
(71, 'KMF', '174', 'CF', 'Komoren-Franc', 'Comorian Franc'),
(72, 'KPW', '408', '₩', 'Nordkoreanischer Won', 'North Korean Won'),
(73, 'KRW', '410', '₩', 'Südkoreanischer Won', 'South Korean Won'),
(74, 'KWD', '414', 'د.ك', 'Kuwait-Dinar', 'Kuwaiti Dinar'),
(75, 'KYD', '136', '$', 'Kaiman-Dollar', 'Cayman Islands Dollar'),
(76, 'KZT', '398', '〒', 'Kasachischer Tenge', 'Kazakhstani Tenge'),
(77, 'LAK', '418', '₭', 'Laotischer Kip', 'Laotian Kip'),
(78, 'LBP', '422', 'ل.ل.', 'Libanesisches Pfund', 'Lebanese Pound'),
(79, 'LKR', '144', '₨', 'Sri-Lanka-Rupie', 'Sri Lankan Rupee'),
(80, 'LRD', '430', '$', 'Liberianischer Dollar', 'Liberian Dollar'),
(81, 'LSL', '426', 'L', 'Lesothischer Loti', 'Lesotho Loti'),
(82, 'LYD', '434', 'ل.د', 'Libyscher Dinar', 'Libyan Dinar'),
(83, 'MAD', '504', 'د.م.', 'Marokkanischer Dirham', 'Moroccan Dirham'),
(84, 'MDL', '498', 'L', 'Moldauischer Leu', 'Moldovan Leu'),
(85, 'MGA', '969', 'Ar', 'Madagaskar-Ariary', 'Malagasy Ariary'),
(86, 'MKD', '807', 'ден', 'Mazedonischer Denar', 'Macedonian Denar'),
(87, 'MMK', '104', 'Ks', 'Myanmarischer Kyat', 'Myanma Kyat'),
(88, 'MNT', '496', '₮', 'Mongolischer Tögrög', 'Mongolian Tugrik'),
(89, 'MOP', '446', 'P', 'Macau-Pataca', 'Macanese Pataca'),
(90, 'MRU', '929', 'UM', 'Mauretanischer Ouguiya', 'Mauritanian Ouguiya'),
(91, 'MUR', '480', '₨', 'Mauritius-Rupie', 'Mauritian Rupee'),
(92, 'MVR', '462', '.ރ', 'Malediven-Rufiyaa', 'Maldivian Rufiyaa'),
(93, 'MWK', '454', 'MK', 'Malawi-Kwacha', 'Malawian Kwacha'),
(94, 'MXN', '484', '$', 'Mexikanischer Peso', 'Mexican Peso'),
(95, 'MYR', '458', 'RM', 'Malaysischer Ringgit', 'Malaysian Ringgit'),
(96, 'MZN', '943', 'MT', 'Moçambique-Metical', 'Mozambican Metical'),
(97, 'NAD', '516', '$', 'Namibia-Dollar', 'Namibian Dollar'),
(98, 'NGN', '566', '₦', 'Nigerianischer Naira', 'Nigerian Naira'),
(99, 'NIO', '132', 'C$', 'Nicaragua-Córdoba', 'Nicaraguan Córdoba'),
(100, 'NOK', '578', 'kr', 'Norwegische Krone', 'Norwegian Krone'),
(101, 'NPR', '524', '₨', 'Nepalesische Rupie', 'Nepalese Rupee'),
(102, 'NZD', '554', '$', 'Neuseeland-Dollar', 'New Zealand Dollar'),
(103, 'OMR', '512', 'ر.ع.', 'Omanischer Rial', 'Omani Rial'),
(104, 'PAB', '590', 'B/.', 'Panamaischer Balboa', 'Panamanian Balboa'),
(105, 'PEN', '604', 'S/.', 'Peruanischer Sol', 'Peruvian Sol'),
(106, 'PGK', '598', 'K', 'Papua-Neuguinea-Kina', 'Papua New Guinean Kina'),
(107, 'PHP', '608', '₱', 'Philippinischer Peso', 'Philippine Peso'),
(108, 'PKR', '586', '₨', 'Pakistanische Rupie', 'Pakistani Rupee'),
(109, 'PLN', '985', 'zł', 'Polnischer Złoty', 'Polish Zloty'),
(110, 'PYG', '600', '₲', 'Paraguayischer Guaraní', 'Paraguayan Guarani'),
(111, 'QAR', '634', 'ر.ق', 'Katar-Riyal', 'Qatari Rial'),
(112, 'RON', '946', 'lei', 'Rumänischer Leu', 'Romanian Leu'),
(113, 'RSD', '941', 'дин.', 'Serbischer Dinar', 'Serbian Dinar'),
(114, 'RUB', '643', '₽', 'Russischer Rubel', 'Russian Ruble'),
(115, 'RWF', '646', 'FR', 'Ruanda-Franc', 'Rwandan Franc'),
(116, 'SAR', '682', 'ر.س', 'Saudi-Riyal', 'Saudi Riyal'),
(117, 'SBD', '90', '$', 'Salomonen-Dollar', 'Solomon Islands Dollar'),
(118, 'SCR', '690', '₨', 'Seychellen-Rupie', 'Seychellois Rupee'),
(119, 'SDG', '938', '£', 'Sudanesisches Pfund', 'Sudanese Pound'),
(120, 'SEK', '752', 'kr', 'Schwedische Krone', 'Swedish Krona'),
(121, 'SGD', '702', '$', 'Singapur-Dollar', 'Singapore Dollar'),
(122, 'SHP', '654', '£', 'St.-Helena-Pfund', 'Saint Helena Pound'),
(123, 'SLL', '694', 'Le', 'Sierra-leonischer Leone', 'Sierra Leonean Leone'),
(124, 'SOS', '706', 'Sh', 'Somalia-Schilling', 'Somali Shilling'),
(125, 'SRD', '740', '$', 'Suriname-Dollar', 'Surinamese Dollar'),
(126, 'SSP', '728', '£', 'Südsudanesisches Pfund', 'South Sudanese Pound'),
(127, 'STN', '930', 'Db', 'São-toméischer Dobra', 'Sao Tome and Principe Dobra'),
(128, 'SYP', '760', '£', 'Syrisches Pfund', 'Syrian Pound'),
(129, 'SZL', '748', 'L', 'Eswatini-Lilangeni', 'Swazi Lilangeni'),
(130, 'THB', '764', '฿', 'Thailändischer Baht', 'Thai Baht'),
(131, 'TJS', '934', 'ЅМ', 'Tadschikischer Somoni', 'Tajikistani Somoni'),
(132, 'TMT', '934', 'm', 'Turkmenistan-Manat', 'Turkmenistani Manat'),
(133, 'TND', '788', 'د.ت', 'Tunesischer Dinar', 'Tunisian Dinar'),
(134, 'TOP', '776', 'T$', 'Tongaischer Paʻanga', 'Tongan Paʻanga'),
(135, 'TRY', '949', '₺', 'Türkische Lira', 'Turkish Lira'),
(136, 'TTD', '780', 'TT$', 'Trinidad-und-Tobago-Dollar', 'Trinidad and Tobago Dollar'),
(137, 'TWD', '901', 'NT$', 'Neuer Taiwan-Dollar', 'New Taiwan Dollar'),
(138, 'TZS', '834', 'T/', 'Tansania-Schilling', 'Tanzanian Shilling'),
(139, 'UAH', '980', '₴', 'Ukrainische Hrywnja', 'Ukrainian Hryvnia'),
(140, 'UGX', '800', 'USh', 'Uganda-Schilling', 'Ugandan Shilling'),
(141, 'USD', '840', '$', 'US-Dollar', 'US Dollar'),
(142, 'UYU', '858', '$', 'Uruguayischer Peso', 'Uruguayan Peso'),
(143, 'UZS', '860', 'UZS', 'Usbekischer Soʻm', 'Uzbekistani Som'),
(144, 'VES', '928', 'Bs.', 'Venezolanischer Bolívar', 'Venezuelan Bolívar'),
(145, 'VND', '704', '₫', 'Vietnamesischer Đồng', 'Vietnamese Dong'),
(146, 'VUV', '548', 'Vt', 'Vanuatu-Vatu', 'Vanuatu Vatu'),
(147, 'WST', '876', 'T', 'Samoa-Tala', 'Samoan Tala'),
(148, 'XAF', '950', 'Fr', 'Zentralafrikanischer CFA-Franc', 'CFA Franc BEAC'),
(149, 'XCD', '951', '$', 'Ostkaribischer Dollar', 'East Caribbean Dollar'),
(150, 'XOF', '952', 'Fr', 'Westafrikanischer CFA-Franc', 'CFA Franc BCEAO');

-- Country Currencies
INSERT INTO country_currencies (country_id, currency_id) VALUES
(1, 44),
(2, 1),
(3, 2),
(4, 149),
(5, 149),
(6, 3),
(7, 4),
(8, 6),
(10, 7),
(11, 141),
(12, 44),
(13, 8),
(14, 9),
(15, 44),
(16, 10),
(17, 11),
(18, 12),
(19, 13),
(20, 44),
(21, 150),
(22, 14),
(23, 15),
(24, 16),
(25, 150),
(26, 44),
(27, 17),
(28, 18),
(29, 19),
(30, 141),
(31, 20),
(32, 21),
(33, 22),
(34, 100),
(35, 23),
(36, 24),
(37, 25),
(38, 26),
(39, 8),
(40, 27),
(41, 148),
(42, 148),
(43, 28),
(44, 150),
(45, 101),
(46, 29),
(47, 148),
(48, 30),
(49, 31),
(50, 32),
(51, 33),
(51, 34),
(52, 35),
(53, 5),
(54, 8),
(55, 44),
(56, 36),
(57, 44),
(58, 37),
(59, 38),
(60, 149),
(61, 39),
(62, 40),
(63, 141),
(64, 44),
(65, 41),
(66, 147),
(67, 42),
(68, 44),
(69, 43),
(70, 44),
(71, 45),
(72, 46),
(73, 141),
(74, 38),
(75, 44),
(76, 148),
(77, 46),
(78, 149),
(79, 47),
(80, 44),
(81, 46),
(82, 48),
(83, 49),
(84, 38),
(85, 50),
(86, 51),
(87, 44),
(88, 148),
(89, 44),
(90, 46),
(91, 52),
(92, 141),
(93, 150),
(94, 53),
(95, 54),
(96, 8),
(97, 55),
(98, 56),
(99, 57),
(100, 58),
(101, 59),
(102, 44),
(103, 60),
(104, 46),
(105, 61),
(106, 46),
(107, 62),
(108, 63),
(109, 64),
(110, 44),
(111, 46),
(112, 65),
(113, 66),
(114, 67),
(115, 68),
(116, 69),
(117, 70),
(118, 8),
(119, 71),
(120, 149),
(121, 72),
(122, 73),
(123, 203);

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
