[free]
name      = Free
customers = 1
projects  = 1
invoices  = 1
web       = true
mobile    = true
api       = false

[small]
name      = Small
customers = 3
projects  = 3
invoices  = 3
web       = true
mobile    = true
api       = false

[medium]
name      = Medium
customers = 10
projects  = 10
invoices  = 10
web       = true
mobile    = true
api       = true

[enterprise]
name      = Enterprise
customers = 1000000
projects  = 1000000
invoices  = 1000000
web       = true
mobile    = true
api       = true
