[free]
name = Free
users = 1
customers = 1
projects = 1
invoices = 1
web = true
mobile = true

[small]
name = Small
users = 5
customers = 3
projects = 3
invoices = 3
web = true
mobile = true

[medium]
name = Medium
users = 50
customers = 10
projects = 10
invoices = 10
web = true
mobile = true
api = true

[enterprise]
name = Enterprise
users = 1000000
customers = 1000000
projects = 1000000
invoices = 1000000
web = true
mobile = true
api = true
