parent=keycloak
import=common/keycloak

styles=css/login.css

# Localization
locales=de,en

# Meta tags
meta=viewport==width=device-width,initial-scale=1

# Logo
kcLogoLink=https://www.smetools.eu
kcLogoTitle=SME Tools
